[versions]
assertj-core = "3.25.3"
wiremock = "3.6.0"
junit-jupiter = "5.10.2"
platform-launcher = "1.10.2"
kotlinx-coroutines-core-jvm = "1.8.1"
kotlin = "2.0.0"
coveralls-jacoco = "1.2.20"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "platform-launcher" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines-core-jvm" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
coveralls-jacoco = { id = "com.github.nbaztec.coveralls-jacoco", version.ref = "coveralls-jacoco" }